theme: jekyll-theme-hacker
title: "The Coffee and The Physics"
author: "milda :)"
description: "This is a place for me to share my thoughts about the world through the lens of a curious physics student who is interested in social issues as well as everything science- and math-related. I hope you enjoy exploring this page :)" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "kunigundosarbata@gmail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
pinterest_username: kunigundosarbata
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
body: {
  background-color: "rgb(102, 141, 171)" ;
}

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme 

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
